# Generated by Django 6.0.6 on 2026-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "truckstop_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=50)),
                ("retail_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["city", "state"], name="fuel_trucks_city_055a31_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuel_trucks_latitud_98babf_idx",
                    ),
                ],
            },
        ),
    ]
